### ISSUE TITLE
bin/run_webpack: line 15: npm: command not found while pushing to heroku

### ISSUE THREAD

**Issue by taqiofficial** [vintasoftware/vinta-boilerplate#55]
I follow all the README Steps for running it local. running locally fine (migration/run-server)
Then
```
heroku create appname
git add -a
git commit -m 'intial commit'
git push heroku master
```

has below error;
```
Counting objects: 87, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (70/70), done.
Writing objects: 100% (87/87), 22.28 KiB | 0 bytes/s, done.
Total 87 (delta 5), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote:  !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
remote:                         Detected buildpacks: Python,Node.js
remote:                         See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
remote: -----> Python app detected
remote: -----> Running pre-compile hook
remote: ----->Pre-compile hook
remote: -----> Running Webpack
remote: jquery-webpack-stats.json created
remote: webpack-stats.json created
remote: bin/run_webpack: line 15: npm: command not found
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to meddy.
remote: 
To https://git.heroku.com/meddy.git
 ! [remote rejected] master -> master (pre-receive hook declined)
```
and the app.json file is ;

```
{
  "name": "appname",
  "description": "Meddy Heroku app.",
  "scripts": {
    "postdeploy": "python manage.py migrate"
  },
  "env": {
    "ALLOWED_HOSTS": {
      "description": "Django ALLOWED_HOSTS setting, e.g.: .appname.herokuapp.com"
    },
    "DISABLE_COLLECTSTATIC": {
      "description": "Heroku setting to disable Django collectstatic (it is run by bin/post_compile)",
      "value": "1"
    },
    "DJANGO_SETTINGS_MODULE": {
      "description": "Django settings Python import path",
      "value": "appname.settings.production"
    },
    "SECRET_KEY": {
      "description": "Django SECRET_KEY setting",
      "generator": "secret"
    }
  },
  "formation": {
    "web": {
      "quantity": 1,
      "size": "free"
    },
    "worker": {
      "quantity": 1,
      "size": "free"
    }
  },
  "addons": [
    {
      "plan": "heroku-postgresql:hobby-dev",
      "options": {
        "version": "9.5"
      },
      "as": "DATABASE"
    },
    {
      "plan": "heroku-redis:hobby-dev",
      "options": {
        "version": "3.2"
      },
      "as": "REDIS"
    },
    {
      "plan": "sendgrid:starter"
    },
    {
      "plan": "papertrail:choklad"
    },
    {
      "plan": "opbeat:test"
    }
  ],
  "buildpacks": [
    {
      "url": "heroku/nodejs"
    },
    {
      "url": "heroku/python"
    }
  ]
}
```

PS : I don't want to host repo on git and[ deploy via Button](https://devcenter.heroku.com/articles/heroku-button#adding-the-heroku-button).

**Comment by andersonresende** [comment]
@taqiofficial Thanks! I will check this issue!

**Comment by aericson** [comment]
Looks like this could be the order of the build packs. Could you try going g on the settings of the app on heroku and adding the build packs:
1. Node.js
2. Python 

In that order.

**Comment by aericson** [comment]
Another note. When you create the app manually heroku doesn't use app.json. So you kind of have to see what is on app.json and configure it yourself.

**Comment by andersonresende** [comment]
@aericson I think this is the problem!

**Comment by taqiofficial** [comment]
I have added the Build pack in Order Node.js and Python Respectively. Add all configs in app.json on heroku manually. 
Now NPM error;


```
emote: webpack-stats.json created
remote: 
remote: > meddy-frontend@0.0.1 build /tmp/build_2bc596adb3ccb1a6d577dc6c44875f82
remote: > NODE_ENV=production webpack -p --progress --colors --config webpack.prod.config.js --bail
remote:                                                                                                                                    69% 176/177 build modulesModuleBuildError: Module build failed: ModuleBuildError: Module build failed: 
remote: undefined
remote: ^
remote:       File to import not found or unreadable: ../bootstrap/scss/_animation
remote: Parent style sheet: stdin
remote:       in /tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/bootstrap-loader/no-op.js (line 13, column 1)
remote:     at DependenciesBlock.onModuleBuildFailed (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
remote:     at nextLoader (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
remote:     at /tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
remote:     at context.callback (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
remote:     at Object.onRender (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/index.js:273:13)
remote:     at Object.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/node_modules/async/dist/async.js:2237:31)
remote:     at apply (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/node_modules/async/dist/async.js:20:25)
remote:     at Object.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/node_modules/async/dist/async.js:56:12)
remote:     at Object.callback (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/node_modules/async/dist/async.js:843:16)
remote:     at options.error (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/node-sass/lib/index.js:289:32)
remote:     at DependenciesBlock.onModuleBuildFailed (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:315:19)
remote:     at DependenciesBlock.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:228:39)
remote:     at context.callback (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
remote:     at Object.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/extract-text-webpack-plugin/loader.js:82:20)
remote:     at Compiler.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack/lib/Compiler.js:204:18)
remote:     at Compiler.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack/lib/Compiler.js:395:18)
remote:     at /tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/tapable/lib/Tapable.js:99:11
remote:     at Compilation.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack/lib/Compilation.js:433:11)
remote:     at errorAndCallback (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack/lib/Compilation.js:340:3)
remote:     at Compilation.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack/lib/Compilation.js:400:12)
remote:     at /tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack/lib/Compilation.js:123:4
remote:     at Array.forEach (native)
remote:     at callback (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack/lib/Compilation.js:122:12)
remote:     at Compilation.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack/lib/Compilation.js:137:11)
remote:     at DependenciesBlock.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack/lib/NormalModule.js:85:18)
remote:     at DependenciesBlock.onModuleBuildFailed (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:315:10)
remote:     at nextLoader (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:270:31)
remote:     at /tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:292:15
remote:     at context.callback (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/webpack-core/lib/NormalModuleMixin.js:148:14)
remote:     at Object.onRender (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/index.js:273:13)
remote:     at Object.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/node_modules/async/dist/async.js:2237:31)
remote:     at apply (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/node_modules/async/dist/async.js:20:25)
remote:     at Object.<anonymous> (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/node_modules/async/dist/async.js:56:12)
remote:     at Object.callback (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/sass-loader/node_modules/async/dist/async.js:843:16)
remote:     at options.error (/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/node_modules/node-sass/lib/index.js:289:32)
remote: 
remote: npm ERR! Linux 3.13.0-110-generic
remote: npm ERR! argv "/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/.heroku/node/bin/node" "/tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/.heroku/node/bin/npm" "run" "build"
remote: npm ERR! node v6.10.0
remote: npm ERR! npm  v3.10.10
remote: npm ERR! code ELIFECYCLE
remote: npm ERR! meddy-frontend@0.0.1 build: `NODE_ENV=production webpack -p --progress --colors --config webpack.prod.config.js --bail`
remote: npm ERR! Exit status 1
remote: npm ERR! 
remote: npm ERR! Failed at the meddy-frontend@0.0.1 build script 'NODE_ENV=production webpack -p --progress --colors --config webpack.prod.config.js --bail'.
remote: npm ERR! Make sure you have the latest version of node.js and npm installed.
remote: npm ERR! If you do, this is most likely a problem with the meddy-frontend package,
remote: npm ERR! not with npm itself.
remote: npm ERR! Tell the author that this fails on your system:
remote: npm ERR!     NODE_ENV=production webpack -p --progress --colors --config webpack.prod.config.js --bail
remote: npm ERR! You can get information on how to open an issue for this project with:
remote: npm ERR!     npm bugs meddy-frontend
remote: npm ERR! Or if that isn't available, you can get their info via:
remote: npm ERR!     npm owner ls meddy-frontend
remote: npm ERR! There is likely additional logging output above.
remote: 
remote: npm ERR! Please include the following file with any support request:
remote: npm ERR!     /tmp/build_2bc596adb3ccb1a6d577dc6c44875f82/npm-debug.log
remote:  !     Push rejected, failed to compile Python app.
remote: 
remote:  !     Push failed

```

**Comment by andersonresende** [comment]
@taqiofficial Just worked to me! Please, send me your `npm freeze` output.

**Comment by taqiofficial** [comment]
@andersonresende npm shrinkwrap works for me, 
```
npm WARN shrinkwrap Excluding devDependency: eslint@3.17.1 { autoprefixer: '^6.7.6',
npm WARN shrinkwrap   'babel-cli': '^6.23.0',
npm WARN shrinkwrap   'babel-core': '^6.23.1',
npm WARN shrinkwrap   'babel-loader': '^6.4.0',
npm WARN shrinkwrap   'babel-preset-es2015': '^6.22.0',
npm WARN shrinkwrap   'babel-preset-react': '^6.23.0',
npm WARN shrinkwrap   bootstrap: '^4.0.0-alpha.4',
npm WARN shrinkwrap   'bootstrap-loader': '^1.3.3',
npm WARN shrinkwrap   classnames: '^2.2.5',
npm WARN shrinkwrap   'css-loader': '^0.25.0',
npm WARN shrinkwrap   'expose-loader': '^0.7.3',
npm WARN shrinkwrap   'extract-text-webpack-plugin': '^1.0.1',
npm WARN shrinkwrap   'file-loader': '^0.9.0',
npm WARN shrinkwrap   'imports-loader': '^0.6.5',
npm WARN shrinkwrap   jquery: '^2.2.4',
npm WARN shrinkwrap   lodash: '^4.17.4',
npm WARN shrinkwrap   marked: '^0.3.6',
npm WARN shrinkwrap   'node-sass': '^3.13.1',
npm WARN shrinkwrap   postcss: '^5.2.16',
npm WARN shrinkwrap   'postcss-loader': '^1.3.3',
npm WARN shrinkwrap   react: '^15.4.2',
npm WARN shrinkwrap   'react-dom': '^15.4.2',
npm WARN shrinkwrap   redux: '^3.6.0',
npm WARN shrinkwrap   'resolve-url-loader': '^1.6.1',
npm WARN shrinkwrap   'sass-loader': '^4.1.1',
npm WARN shrinkwrap   'script-loader': '^0.7.0',
npm WARN shrinkwrap   'style-loader': '^0.13.2',
npm WARN shrinkwrap   'url-loader': '^0.5.8',
npm WARN shrinkwrap   webpack: '^1.14.0',
npm WARN shrinkwrap   'webpack-bundle-tracker': '0.0.93',
npm WARN shrinkwrap   'webpack-dev-server': '^1.16.3',
npm WARN shrinkwrap   'webpack-spritesmith': '^0.2.6' }
npm WARN shrinkwrap Excluding devDependency: eslint-config-airbnb@12.0.0 { autoprefixer: '^6.7.6',
npm WARN shrinkwrap   'babel-cli': '^6.23.0',
npm WARN shrinkwrap   'babel-core': '^6.23.1',
npm WARN shrinkwrap   'babel-loader': '^6.4.0',
npm WARN shrinkwrap   'babel-preset-es2015': '^6.22.0',
npm WARN shrinkwrap   'babel-preset-react': '^6.23.0',
npm WARN shrinkwrap   bootstrap: '^4.0.0-alpha.4',
npm WARN shrinkwrap   'bootstrap-loader': '^1.3.3',
npm WARN shrinkwrap   classnames: '^2.2.5',
npm WARN shrinkwrap   'css-loader': '^0.25.0',
npm WARN shrinkwrap   'expose-loader': '^0.7.3',
npm WARN shrinkwrap   'extract-text-webpack-plugin': '^1.0.1',
npm WARN shrinkwrap   'file-loader': '^0.9.0',
npm WARN shrinkwrap   'imports-loader': '^0.6.5',
npm WARN shrinkwrap   jquery: '^2.2.4',
npm WARN shrinkwrap   lodash: '^4.17.4',
npm WARN shrinkwrap   marked: '^0.3.6',
npm WARN shrinkwrap   'node-sass': '^3.13.1',
npm WARN shrinkwrap   postcss: '^5.2.16',
npm WARN shrinkwrap   'postcss-loader': '^1.3.3',
npm WARN shrinkwrap   react: '^15.4.2',
npm WARN shrinkwrap   'react-dom': '^15.4.2',
npm WARN shrinkwrap   redux: '^3.6.0',
npm WARN shrinkwrap   'resolve-url-loader': '^1.6.1',
npm WARN shrinkwrap   'sass-loader': '^4.1.1',
npm WARN shrinkwrap   'script-loader': '^0.7.0',
npm WARN shrinkwrap   'style-loader': '^0.13.2',
npm WARN shrinkwrap   'url-loader': '^0.5.8',
npm WARN shrinkwrap   webpack: '^1.14.0',
npm WARN shrinkwrap   'webpack-bundle-tracker': '0.0.93',
npm WARN shrinkwrap   'webpack-dev-server': '^1.16.3',
npm WARN shrinkwrap   'webpack-spritesmith': '^0.2.6' }
npm WARN shrinkwrap Excluding devDependency: eslint-plugin-import@1.16.0 { autoprefixer: '^6.7.6',
npm WARN shrinkwrap   'babel-cli': '^6.23.0',
npm WARN shrinkwrap   'babel-core': '^6.23.1',
npm WARN shrinkwrap   'babel-loader': '^6.4.0',
npm WARN shrinkwrap   'babel-preset-es2015': '^6.22.0',
npm WARN shrinkwrap   'babel-preset-react': '^6.23.0',
npm WARN shrinkwrap   bootstrap: '^4.0.0-alpha.4',
npm WARN shrinkwrap   'bootstrap-loader': '^1.3.3',
npm WARN shrinkwrap   classnames: '^2.2.5',
npm WARN shrinkwrap   'css-loader': '^0.25.0',
npm WARN shrinkwrap   'expose-loader': '^0.7.3',
npm WARN shrinkwrap   'extract-text-webpack-plugin': '^1.0.1',
npm WARN shrinkwrap   'file-loader': '^0.9.0',
npm WARN shrinkwrap   'imports-loader': '^0.6.5',
npm WARN shrinkwrap   jquery: '^2.2.4',
npm WARN shrinkwrap   lodash: '^4.17.4',
npm WARN shrinkwrap   marked: '^0.3.6',
npm WARN shrinkwrap   'node-sass': '^3.13.1',
npm WARN shrinkwrap   postcss: '^5.2.16',
npm WARN shrinkwrap   'postcss-loader': '^1.3.3',
npm WARN shrinkwrap   react: '^15.4.2',
npm WARN shrinkwrap   'react-dom': '^15.4.2',
npm WARN shrinkwrap   redux: '^3.6.0',
npm WARN shrinkwrap   'resolve-url-loader': '^1.6.1',
npm WARN shrinkwrap   'sass-loader': '^4.1.1',
npm WARN shrinkwrap   'script-loader': '^0.7.0',
npm WARN shrinkwrap   'style-loader': '^0.13.2',
npm WARN shrinkwrap   'url-loader': '^0.5.8',
npm WARN shrinkwrap   webpack: '^1.14.0',
npm WARN shrinkwrap   'webpack-bundle-tracker': '0.0.93',
npm WARN shrinkwrap   'webpack-dev-server': '^1.16.3',
npm WARN shrinkwrap   'webpack-spritesmith': '^0.2.6' }
npm WARN shrinkwrap Excluding devDependency: eslint-plugin-jsx-a11y@2.2.3 { autoprefixer: '^6.7.6',
npm WARN shrinkwrap   'babel-cli': '^6.23.0',
npm WARN shrinkwrap   'babel-core': '^6.23.1',
npm WARN shrinkwrap   'babel-loader': '^6.4.0',
npm WARN shrinkwrap   'babel-preset-es2015': '^6.22.0',
npm WARN shrinkwrap   'babel-preset-react': '^6.23.0',
npm WARN shrinkwrap   bootstrap: '^4.0.0-alpha.4',
npm WARN shrinkwrap   'bootstrap-loader': '^1.3.3',
npm WARN shrinkwrap   classnames: '^2.2.5',
npm WARN shrinkwrap   'css-loader': '^0.25.0',
npm WARN shrinkwrap   'expose-loader': '^0.7.3',
npm WARN shrinkwrap   'extract-text-webpack-plugin': '^1.0.1',
npm WARN shrinkwrap   'file-loader': '^0.9.0',
npm WARN shrinkwrap   'imports-loader': '^0.6.5',
npm WARN shrinkwrap   jquery: '^2.2.4',
npm WARN shrinkwrap   lodash: '^4.17.4',
npm WARN shrinkwrap   marked: '^0.3.6',
npm WARN shrinkwrap   'node-sass': '^3.13.1',
npm WARN shrinkwrap   postcss: '^5.2.16',
npm WARN shrinkwrap   'postcss-loader': '^1.3.3',
npm WARN shrinkwrap   react: '^15.4.2',
npm WARN shrinkwrap   'react-dom': '^15.4.2',
npm WARN shrinkwrap   redux: '^3.6.0',
npm WARN shrinkwrap   'resolve-url-loader': '^1.6.1',
npm WARN shrinkwrap   'sass-loader': '^4.1.1',
npm WARN shrinkwrap   'script-loader': '^0.7.0',
npm WARN shrinkwrap   'style-loader': '^0.13.2',
npm WARN shrinkwrap   'url-loader': '^0.5.8',
npm WARN shrinkwrap   webpack: '^1.14.0',
npm WARN shrinkwrap   'webpack-bundle-tracker': '0.0.93',
npm WARN shrinkwrap   'webpack-dev-server': '^1.16.3',
npm WARN shrinkwrap   'webpack-spritesmith': '^0.2.6' }
npm WARN shrinkwrap Excluding devDependency: eslint-plugin-react@6.10.0 { autoprefixer: '^6.7.6',
npm WARN shrinkwrap   'babel-cli': '^6.23.0',
npm WARN shrinkwrap   'babel-core': '^6.23.1',
npm WARN shrinkwrap   'babel-loader': '^6.4.0',
npm WARN shrinkwrap   'babel-preset-es2015': '^6.22.0',
npm WARN shrinkwrap   'babel-preset-react': '^6.23.0',
npm WARN shrinkwrap   bootstrap: '^4.0.0-alpha.4',
npm WARN shrinkwrap   'bootstrap-loader': '^1.3.3',
npm WARN shrinkwrap   classnames: '^2.2.5',
npm WARN shrinkwrap   'css-loader': '^0.25.0',
npm WARN shrinkwrap   'expose-loader': '^0.7.3',
npm WARN shrinkwrap   'extract-text-webpack-plugin': '^1.0.1',
npm WARN shrinkwrap   'file-loader': '^0.9.0',
npm WARN shrinkwrap   'imports-loader': '^0.6.5',
npm WARN shrinkwrap   jquery: '^2.2.4',
npm WARN shrinkwrap   lodash: '^4.17.4',
npm WARN shrinkwrap   marked: '^0.3.6',
npm WARN shrinkwrap   'node-sass': '^3.13.1',
npm WARN shrinkwrap   postcss: '^5.2.16',
npm WARN shrinkwrap   'postcss-loader': '^1.3.3',
npm WARN shrinkwrap   react: '^15.4.2',
npm WARN shrinkwrap   'react-dom': '^15.4.2',
npm WARN shrinkwrap   redux: '^3.6.0',
npm WARN shrinkwrap   'resolve-url-loader': '^1.6.1',
npm WARN shrinkwrap   'sass-loader': '^4.1.1',
npm WARN shrinkwrap   'script-loader': '^0.7.0',
npm WARN shrinkwrap   'style-loader': '^0.13.2',
npm WARN shrinkwrap   'url-loader': '^0.5.8',
npm WARN shrinkwrap   webpack: '^1.14.0',
npm WARN shrinkwrap   'webpack-bundle-tracker': '0.0.93',
npm WARN shrinkwrap   'webpack-dev-server': '^1.16.3',
npm WARN shrinkwrap   'webpack-spritesmith': '^0.2.6' }
npm WARN shrinkwrap Excluding devDependency: react-hot-loader@1.3.1 { autoprefixer: '^6.7.6',
npm WARN shrinkwrap   'babel-cli': '^6.23.0',
npm WARN shrinkwrap   'babel-core': '^6.23.1',
npm WARN shrinkwrap   'babel-loader': '^6.4.0',
npm WARN shrinkwrap   'babel-preset-es2015': '^6.22.0',
npm WARN shrinkwrap   'babel-preset-react': '^6.23.0',
npm WARN shrinkwrap   bootstrap: '^4.0.0-alpha.4',
npm WARN shrinkwrap   'bootstrap-loader': '^1.3.3',
npm WARN shrinkwrap   classnames: '^2.2.5',
npm WARN shrinkwrap   'css-loader': '^0.25.0',
npm WARN shrinkwrap   'expose-loader': '^0.7.3',
npm WARN shrinkwrap   'extract-text-webpack-plugin': '^1.0.1',
npm WARN shrinkwrap   'file-loader': '^0.9.0',
npm WARN shrinkwrap   'imports-loader': '^0.6.5',
npm WARN shrinkwrap   jquery: '^2.2.4',
npm WARN shrinkwrap   lodash: '^4.17.4',
npm WARN shrinkwrap   marked: '^0.3.6',
npm WARN shrinkwrap   'node-sass': '^3.13.1',
npm WARN shrinkwrap   postcss: '^5.2.16',
npm WARN shrinkwrap   'postcss-loader': '^1.3.3',
npm WARN shrinkwrap   react: '^15.4.2',
npm WARN shrinkwrap   'react-dom': '^15.4.2',
npm WARN shrinkwrap   redux: '^3.6.0',
npm WARN shrinkwrap   'resolve-url-loader': '^1.6.1',
npm WARN shrinkwrap   'sass-loader': '^4.1.1',
npm WARN shrinkwrap   'script-loader': '^0.7.0',
npm WARN shrinkwrap   'style-loader': '^0.13.2',
npm WARN shrinkwrap   'url-loader': '^0.5.8',
npm WARN shrinkwrap   webpack: '^1.14.0',
npm WARN shrinkwrap   'webpack-bundle-tracker': '0.0.93',
npm WARN shrinkwrap   'webpack-dev-server': '^1.16.3',
npm WARN shrinkwrap   'webpack-spritesmith': '^0.2.6' }
wrote npm-shrinkwrap.json
```

**Comment by andersonresende** [comment]
@taqiofficial This is preety weird! Please, go to heroku and remove all your buildpacks! After this, add only the nodejs buildpack. Now, try  `git push heroku master`.

**Comment by taqiofficial** [comment]
@andersonresende successfully deployed. But App crashed error on heroku open.

**Comment by taqiofficial** [comment]
When I added python buildback after node.js on heroku then it fails with error i mentioned above.

**Comment by andersonresende** [comment]
I am checking

**Comment by andersonresende** [comment]
@taqiofficial Put the buildpacks back: first node, second python. Remove functools32 from requirements.txt. And change your bootstrap version on package.json: remove the `^`.

**Comment by andersonresende** [comment]
Don't forget to look the app.json and set the enviroment variables on heroku.

**Comment by taqiofficial** [comment]
Works By;
removing pkg-resources==0.0.0 from req.txt file
Changing bootstrap: version from "^4.0.0-alpha.4" to "4.0.0-alpha.4" in package.json

Super Thanks @andersonresende @aericson

**Comment by embs** [comment]
This kind of issue may be mitigated with https://github.com/vintasoftware/django-react-boilerplate/issues/161
